### ISSUE TITLE
[FEATURE] Random Class

### ISSUE THREAD

**Issue by N8python** [MasMas-js/MasMas.js#10]
A **private** discussion about which functions should be in the Random Class.

**Comment by N8python** [comment]
We have getRandomInt()

**Comment by RDIL** [comment]
Let’s just merge getrandomint and getRandomFloat into one getRandomNumber with the float param.  If float is true return a float, else return an int

**Comment by N8python** [comment]
okay - cool

**Comment by RDIL** [comment]
Can you do that?

**Comment by N8python** [comment]
Done!

**Comment by N8python** [comment]
Would you like to move chatting about mas-mas to the google hangout? So we can text each other real time?

**Comment by RDIL** [comment]
Alright sure

**Comment by N8python** [comment]
I'm on the hangout now
