### ISSUE TITLE
[FEATURE] Choose jQuery Version

### ISSUE THREAD

**Issue by RDIL** [MasMas-js/MasMas.js#16]
**Is your feature request related to a problem? Please describe.**
No.  

**Describe the solution you'd like**
A param you can optionally pass to `loadjQuery();` that makes sure to load in a specific version of jQuery.  

**Describe alternatives you've considered**
Leaving it as-is.  

**Additional context**

**Comment by N8python** [comment]
I finished this today!

**Comment by RDIL** [comment]
Oh ok
