### ISSUE TITLE
[BUG] loadScript + loadjQuery don't work

### ISSUE THREAD

**Issue by N8python** [MasMas-js/MasMas.js#2]
**Describe the bug**  
`<script>` tag is added to the head of the HTML, but not implemented

**To Reproduce**  
1. Link MasMas.js  
2. Call loadjQuery()  

**Expected behavior**  
jQuery was supposed to be available after the function call.  

**Desktop (please complete the following information):**  
 - OS: [iOS]  
 - Browser [Chrome]  
 - Version [71]

**Comment by RDIL** [comment]
Huh, that's odd.  Do you think you can fix it or do you need me to do it?

**Comment by N8python** [comment]
I'll try to fix it
